import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import About from "../pages/about";
import Hero from "../pages/hero";
import styles from "../styles/Home.module.css";
import ScrollOberver from "../utils/scroll-observer";
import Contact from "./contact";
import Projects from "./projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lukas Novorolnik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_icon.ico" />
      </Head>

      <main>
        <div className="flex flex-col gap-20">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="fixed left-0 top-0 h-screen w-full object-cover -z-10"
            id="background video dark"
          >
            <source src="BG_video_dark.mp4" type="video/mp4" />
            <source src="BG_video_dark.webm" type="video/webm" />
          </video>

          <Header />
          <Hero />
          <About />
          <Projects />
          <Contact />
        </div>
      </main>
    </div>
  );
}
